//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORdbEntities : DbContext
    {
        public ORdbEntities()
            : base("name=ORdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diakok> diakoks { get; set; }
        public virtual DbSet<karok> karoks { get; set; }
        public virtual DbSet<Kerdes_valaszlehetoseg> Kerdes_valaszlehetoseg { get; set; }
        public virtual DbSet<kerdes_x> kerdes_x { get; set; }
        public virtual DbSet<kerdesek> kerdeseks { get; set; }
        public virtual DbSet<kerdoiv_kerdes> kerdoiv_kerdes { get; set; }
        public virtual DbSet<kerdoivek> kerdoiveks { get; set; }
        public virtual DbSet<szakok> szakoks { get; set; }
        public virtual DbSet<tanarok> tanaroks { get; set; }
        public virtual DbSet<tanszekek> tanszekeks { get; set; }
        public virtual DbSet<tantargyak> tantargyaks { get; set; }
        public virtual DbSet<valaszok> valaszoks { get; set; }
        public virtual DbSet<x> x { get; set; }
    }
}
