//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class diakok
    {
        public int id_diakok { get; set; }
        public string azonosito { get; set; }
        public Nullable<int> id_szakok { get; set; }
        public Nullable<short> evfolyam { get; set; }
        public Nullable<short> kitoltotte1 { get; set; }
        public Nullable<short> kitoltotte2 { get; set; }
    
        public virtual szakok szakok { get; set; }
    }
}
