//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class karok
    {
        public karok()
        {
            this.szakoks = new HashSet<szakok>();
            this.tanszekeks = new HashSet<tanszekek>();
        }
    
        public string nev { get; set; }
        public int id_karok { get; set; }
    
        public virtual ICollection<szakok> szakoks { get; set; }
        public virtual ICollection<tanszekek> tanszekeks { get; set; }
    }
}
