//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class kerdesek
    {
        public kerdesek()
        {
            this.Kerdes_valaszlehetoseg = new HashSet<Kerdes_valaszlehetoseg>();
            this.kerdes_x = new HashSet<kerdes_x>();
            this.valaszoks = new HashSet<valaszok>();
            this.kerdoiv_kerdes = new HashSet<kerdoiv_kerdes>();
        }
    
        public int id_kerdesek { get; set; }
        public string kerdes { get; set; }
        public string tipus { get; set; }
    
        public virtual ICollection<Kerdes_valaszlehetoseg> Kerdes_valaszlehetoseg { get; set; }
        public virtual ICollection<kerdes_x> kerdes_x { get; set; }
        public virtual ICollection<valaszok> valaszoks { get; set; }
        public virtual ICollection<kerdoiv_kerdes> kerdoiv_kerdes { get; set; }
    }
}
