//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class szakok
    {
        public szakok()
        {
            this.diakoks = new HashSet<diakok>();
            this.tantargyaks = new HashSet<tantargyak>();
            this.x = new HashSet<x>();
        }
    
        public int id_szakok { get; set; }
        public string nev { get; set; }
        public Nullable<int> idotartam { get; set; }
        public Nullable<int> id_karok { get; set; }
    
        public virtual ICollection<diakok> diakoks { get; set; }
        public virtual karok karok { get; set; }
        public virtual ICollection<tantargyak> tantargyaks { get; set; }
        public virtual ICollection<x> x { get; set; }
    }
}
