//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanarok
    {
        public tanarok()
        {
            this.x = new HashSet<x>();
        }
    
        public string nev { get; set; }
        public int id_tanarok { get; set; }
        public string tanarok_alias { get; set; }
        public string jelszo { get; set; }
        public string funkcio { get; set; }
        public Nullable<int> id_tanszekek { get; set; }
        public string felhasznalo_tipusa { get; set; }
        public string email { get; set; }
    
        public virtual tanszekek tanszekek { get; set; }
        public virtual ICollection<x> x { get; set; }
    }
}
