//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanszekek
    {
        public tanszekek()
        {
            this.tanaroks = new HashSet<tanarok>();
        }
    
        public int id_tanszekek { get; set; }
        public string nev { get; set; }
        public Nullable<int> id_karok { get; set; }
    
        public virtual karok karok { get; set; }
        public virtual ICollection<tanarok> tanaroks { get; set; }
    }
}
