//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tantargyak
    {
        public tantargyak()
        {
            this.x = new HashSet<x>();
        }
    
        public int id_tantargyak { get; set; }
        public string nev { get; set; }
        public string tipus { get; set; }
        public Nullable<int> id_szakok { get; set; }
    
        public virtual szakok szakok { get; set; }
        public virtual ICollection<x> x { get; set; }
    }
}
