//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class valaszok
    {
        public int id_valaszok { get; set; }
        public Nullable<int> id_kerdoiv { get; set; }
        public Nullable<int> id_kerdes { get; set; }
        public Nullable<int> id_valasz { get; set; }
    
        public virtual Kerdes_valaszlehetoseg Kerdes_valaszlehetoseg { get; set; }
        public virtual kerdesek kerdesek { get; set; }
        public virtual kerdoivek kerdoivek { get; set; }
    }
}
