//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class x
    {
        public x()
        {
            this.kerdes_x = new HashSet<kerdes_x>();
        }
    
        public int id_x { get; set; }
        public Nullable<int> id_tanarok { get; set; }
        public Nullable<int> id_tantargyak { get; set; }
        public Nullable<int> id_szakok { get; set; }
        public Nullable<short> evfolyam { get; set; }
        public Nullable<short> felev { get; set; }
        public string tantargy_tipus { get; set; }
    
        public virtual ICollection<kerdes_x> kerdes_x { get; set; }
        public virtual szakok szakok { get; set; }
        public virtual tanarok tanarok { get; set; }
        public virtual tantargyak tantargyak { get; set; }
    }
}
